---
name: CI

"on":
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    permissions: {}
    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: YAML Lint
            recipe: lint-yaml
            pip: yamllint
          - name: ShellCheck
            recipe: lint-shell
            apt: shellcheck
          - name: VCS Validate
            recipe: validate-manifest
            pip: vcs2l
          - name: Codespell
            recipe: lint-spelling
            pip: codespell
          - name: Actionlint
            recipe: lint-actions
            actionlint: true
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Install just
        run: sudo apt-get update && sudo apt-get install -y just
      - name: Install pip tool
        if: ${{ matrix.pip }}
        run: pip install ${{ matrix.pip }}
      - name: Install apt tool
        if: ${{ matrix.apt }}
        run: sudo apt-get install -y ${{ matrix.apt }}
      - name: Install actionlint
        if: ${{ matrix.actionlint }}
        run: |
          bash <(curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          sudo mv actionlint /usr/local/bin/
      - name: Run linter
        run: just ${{ matrix.recipe }}

  pre-commit:
    permissions: {}
    name: Pre-commit
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: "3.x"
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
        with:
          extra_args: --all-files --verbose
