---
name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    permissions: {}
    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: YAML Lint
            pip: yamllint
            run: yamllint --strict .
          - name: ShellCheck
            apt: shellcheck
            run: shellcheck scripts/update_workspace.sh
          - name: VCS Validate
            pip: vcs2l
            run: vcs validate --input repos.yaml
          - name: Codespell
            pip: codespell
            run: codespell --ignore-words=.codespell-ignore
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Install pip tool
        if: ${{ matrix.pip }}
        run: pip install ${{ matrix.pip }}
      - name: Install apt tool
        if: ${{ matrix.apt }}
        run: sudo apt-get update && sudo apt-get install -y ${{ matrix.apt }}
      - name: Run linter
        run: ${{ matrix.run }}

  actionlint:
    permissions: {}
    name: Actionlint
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Run actionlint
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca  # v1.7.12
        with:
          args: -color
