---
name: CI

"on":
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    permissions: {}
    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: YAML Lint
            recipe: lint-yaml
            pip: yamllint
          - name: ShellCheck
            recipe: lint-shell
            apt: shellcheck
          - name: VCS Validate
            recipe: validate-manifest
            pip: vcs2l
          - name: Codespell
            recipe: lint-spelling
            pip: codespell
          - name: Actionlint
            recipe: lint-actions
            actionlint: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - name: Install just
        run: sudo apt-get update && sudo apt-get install -y just
      - name: Install pip tool
        if: ${{ matrix.pip }}
        run: pip install ${{ matrix.pip }}
      - name: Install apt tool
        if: ${{ matrix.apt }}
        run: sudo apt-get install -y ${{ matrix.apt }}
      - name: Install actionlint
        if: ${{ matrix.actionlint }}
        run: |
          bash <(curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          sudo mv actionlint /usr/local/bin/
      - name: Run linter
        run: just ${{ matrix.recipe }}

  zizmor:
    permissions: {}
    name: Zizmor
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d  # v0.5.6
        with:
          advanced-security: "false"
          annotations: "true"

  pre-commit:
    permissions: {}
    name: Pre-commit
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5.4.0
        with:
          python-version: "3.x"
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
        with:
          extra_args: --all-files --verbose
