---
name: DCO

on:
  pull_request:
    branches: [main]

permissions: {}

jobs:
  dco:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - uses: KineticCafe/actions-dco@1da04282bbf757dab7d92a5c8535dbfb8113da5c  # v3.1.0
        with:
          exempt-authors: "@robotsix.local"
