---
name: Link Check

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"  # Monday mornings

permissions: {}

jobs:
  lychee:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8  # v2.9.0
        with:
          args: --no-progress '*.md' '**/*.md'
